# Generated by Django 4.2.4 on 2023-08-11 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='data join')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(choices=[(False, 'admin'), (True, 'user')], default=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.DateField(default=datetime.date(2023, 8, 12))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
